### ISSUE TITLE
Anonymization adjusts timestamps and creates submission times in the future

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dolos#1104] opened 2023-04-24 16:20 UTC
I was somewhat surprised to see that timestamps are adjusted when in anonymous mode, as this gave me a submission date in the future. This is a view on April 24, 2023:

![image](https://user-images.githubusercontent.com/5736113/234056306-1bcc2452-97a8-462d-9043-1ccbe477b23d.png)

Is this by design?

Also dates are formatted in Dutch locale, where all other information in Dolos is given in English.

**Comment by rien** [comment] 2023-04-25 07:37
This is intentional, since specific submission times can easily be used to de-anonymize the submission. There is a fixed (random) offset applied to all submissions. The fact that the offset can cause submissions in the future is not by design and should indeed be fixed to avoid confusion.

The date formatting was fixed in #1087, but is not released yet.

**Closed** 2023-04-28 12:03 UTC
Labels: bug, question
